function [TWD, Withdrawals, W, IN, Meta] = loadWithdrawalData(varargin)

% GCAM
load(fullfile( ...
   getenv('MATLAB_ACTIVE_PROJECT_PATH'),'data','matfiles','GCAM_waterdemand'), ...
   'TWD');

% DRBC
load(fullfile( ...
   setpath('icom/DRBC/withdrawals','data'),'withdrawals'), ...
   'Withdrawals','Meta');

% remapping weights
load(fullfile( ...
   getenv('MATLAB_ACTIVE_PROJECT_PATH'),'data','matfiles','weights'), ...
   'W','IN');